[workspace]
resolver = "2"
members = [
    "xwf_api_rs",
    "examples/xt-helloworld-rs",
    "examples/xt-count-items-rs",
]


[patch.'https://github.com/ThomasVogl/xwf-api-rs.git']
xwf-api-rs = { path = "./xwf_api_rs"}