[package]
name = "xwf-api-rs"
version = "1.1.0-dev"
edition = "2021"
authors = ["Thomas Vogl <thomas.vogl@respon.se>" ]
description = "Unofficial Rust Bindings for X-Ways Forensics X-Tension API"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cstr = "0.2.12"
winapi = { version="0.3.9", features = ["consoleapi", "minwindef", "ntdef", "libloaderapi"] }
bitflags = { version = "2.8.0", features = ["serde"] }
chrono = {  version = "0.4.39", features = ["serde"] }
serde = { version = "1.0.217", features = ["derive"] }
regex = "1.11.1"
winsafe = { version = "0.0.22", features = ["kernel"]}

[lib]
crate-type = ["lib"]

[features]
default = [ "api_20_9" ]
api_21_3 = [ "api_21_2" ]
api_21_2 = [ "api_21_1" ]
api_21_1 = [ "api_21_0" ]
api_21_0 = [ "api_20_9" ]
api_20_9 = [ "api_20_8" ]
api_20_8 = [ "api_20_7" ]
api_20_7 = [ "api_20_6" ]
api_20_6 = [ "api_20_5" ]
api_20_5 = [ "api_20_4" ]
api_20_4 = [ "api_20_3" ]
api_20_3 = [ "api_20_2" ]
api_20_2 = [ "api_20_1" ]
api_20_1 = [ ]
debug_output = [ ]
strict_enum_checking = [ ]
